[package]
name = "gomori_bot_utils"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gomori = { path = "../gomori" }
serde_json = "1.0.118"
anyhow = "1.0.86"
